/**
 * @file PerlinNoise.cpp
 * @brief Implementation of PerlinNoise class for 3D smooth noise generation.
 *
 * This class implements the classic Perlin Noise algorithm created by Ken Perlin.
 * The generated noise is continuous, smooth and widely used in:
 *  - Terrain generation
 *  - Natural effects (clouds, fire, water)
 *  - Procedural shading
 *  - Programmatically generated textures
 *
 * The class supports classic 3D noise and multi-octave noise.
 */

#include "../../include/terrain-generator/PerlinNoise.h"
#include <algorithm>
#include <numeric>
#include <random>
#include <cmath>

/**
 * @brief Default constructor using Ken Perlin's classic permutation.
 *
 * This permutation table produces standard deterministic noise.
 * The internal vector `p` contains 512 elements where the first 256 are
 * duplicated at the end, facilitating wrap-around operations.
 */
PerlinNoise::PerlinNoise() {
    // Standard Ken Perlin permutation
    std::vector<int> permutation = {
        151,160,137,91,90,15,131,13,201,95,96,53,194,233,7,225,
        140,36,103,30,69,142,8,99,37,240,21,10,23,190,6,148,
        247,120,234,75,0,26,197,62,94,252,219,203,117,35,11,32,
        57,177,33,88,237,149,56,87,174,20,125,136,171,168,68,
        175,74,165,71,134,139,48,27,166,77,146,158,231,83,111,
        229,122,60,211,133,230,220,105,92,41,55,46,245,40,244,
        102,143,54,65,25,63,161,1,216,80,73,209,76,132,187,208,
        89,18,169,200,196,135,130,116,188,159,86,164,100,109,
        198,173,186,3,64,52,217,226,250,124,123,5,202,38,147,
        118,126,255,82,85,212,207,206,59,227,47,16,58,17,182,
        189,28,42,223,183,170,213,119,248,152,2,44,154,163,70,
        221,153,101,155,167,43,172,9,129,22,39,253,19,98,108,
        110,79,113,224,232,178,185,112,104,218,246,97,228,251,
        34,242,193,238,210,144,12,191,179,162,241,81,51,145,235,
        249,14,239,107,49,192,214,31,181,199,106,157,184,84,204,
            176,115,121,50,45,127,4,150,254,138,236,205,93,222,114,
            67,29,24,72,243,141,128,195,78,66,215,61,156,180
    };

    p.resize(512);
    for (int i = 0; i < 256; i++) {
        p[256 + i] = p[i] = permutation[i];
    }
}

/**
 * @brief Constructor using a seed to generate random permutation.
 *
 * @param seed Value to initialize deterministic generator.
 *
 * This method creates a different noise variation purely based on the seed,
 * allowing reproducible procedural generation.
 */
PerlinNoise::PerlinNoise(unsigned int seed) {
    p.resize(512);
    std::vector<int> permutation(256);
    std::iota(permutation.begin(), permutation.end(), 0);

    std::default_random_engine engine(seed);
    std::shuffle(permutation.begin(), permutation.end(), engine);

    for (int i = 0; i < 256; i++) {
        p[256 + i] = p[i] = permutation[i];
    }
}

/**
 * @brief Smoothing function (fade) used by Ken Perlin.
 *
 * The function:
 *      6t⁵ - 15t⁴ + 10t³
 *
 * provides C2 smoothness (second derivative continuity),
 * essential for eliminating artifacts.
 */
double PerlinNoise::fade(double t) {
    return t * t * t * (t * (t * 6 - 15) + 10);
}


/**
 * @brief Linear interpolation (lerp).
 *
 * @param t Interpolation parameter (0 → a, 1 → b)
 * @param a Start value
 * @param b End value
 */
double PerlinNoise::lerp(double t, double a, double b) {
    return a + t * (b - a);
}

/**
 * @brief Calculates dot-product between pseudo-random gradient and offset vector.
 *
 * @param hash Hash of gradient generated by permutation
 * @param x offset X
 * @param y offset Y
 * @param z offset Z
 *
 * Gradient selection depends on the lower 4 bits of the hash.
 */
double PerlinNoise::grad(int hash, double x, double y, double z) {
    int h = hash & 15;
    double u = h < 8 ? x : y;
    double v = h < 4 ? y : (h == 12 || h == 14 ? x : z);
    return ((h & 1) == 0 ? u : -u) + ((h & 2) == 0 ? v : -v);
}

/**
 * @brief Calculates 3D Perlin Noise.
 *
 * The function follows the original implementation combining:
 *  - Gradients
 *  - Fade curves
 *  - Trilinear interpolation
 *
 * @param x X coordinate
 * @param y Y coordinate
 * @param z Z coordinate
 *
 * @return Noise value between [-1, 1]
 */
double PerlinNoise::noise(double x, double y, double z) {

    // Locates grid cells
    int X = (int)floor(x) & 255;
    int Y = (int)floor(y) & 255;
    int Z = (int)floor(z) & 255;

    // Internal distances
    x -= floor(x);
    y -= floor(y);
    z -= floor(z);

    // Smoothing curves
    double u = fade(x);
    double v = fade(y);
    double w = fade(z);

    // Hashes of the 8 cell corners
    int A = p[X] + Y;
    int AA = p[A] + Z;
    int AB = p[A + 1] + Z;
    int B = p[X + 1] + Y;
    int BA = p[B] + Z;
    int BB = p[B + 1] + Z;

    // Complete trilinear interpolation
    return lerp(w, lerp(v, lerp(u, grad(p[AA], x, y, z),
                                   grad(p[BA], x - 1, y, z)),
                           lerp(u, grad(p[AB], x, y - 1, z),
                                   grad(p[BB], x - 1, y - 1, z))),
                   lerp(v, lerp(u, grad(p[AA + 1], x, y, z - 1),
                                   grad(p[BA + 1], x - 1, y, z - 1)),
                           lerp(u, grad(p[AB + 1], x, y - 1, z - 1),
                                   grad(p[BB + 1], x - 1, y - 1, z - 1))));
}

/**
 * @brief Generates multi-octave Perlin Noise (fractal noise).
 *
 * @param x X coordinate
 * @param y Y coordinate
 * @param octaves Number of octaves (layers)
 * @param persistence Amplitude reduction per octave (0–1)
 *
 * The final noise is a weighted sum of multiple layers:
 *
 *      total += noise(x * freq) * amp
 *
 * @return Normalized noise value in [-1, 1]
 */
double PerlinNoise::octaveNoise(double x, double y, int octaves, double persistence) {
    double total = 0.0;
    double frequency = 1.0;
    double amplitude = 1.0;
    double maxValue = 0.0;

    for (int i = 0; i < octaves; i++) {
        total += noise(x * frequency, y * frequency, 0.0) * amplitude;
        maxValue += amplitude;
        amplitude *= persistence;
        frequency *= 2.0;
    }

    return total / maxValue;
}